AWSTemplateFormatVersion: 2010-09-09
Description: 
  Template to create a VPC with IGW and enabled public IP.
  Once deleting stack, we should delete the associated S3 bucket.

Parameters:
  # CIDR of VPC
  NetworkCIDR:
    Description: CIDR of the new VPC
    Type: String
    Default: 10.0.0.0/16

  # AZ Name where subnet will be created
  AvailabilityZoneName:
    Description: CIDR of the new VPC
    Type: AWS::EC2::AvailabilityZone::Name
    Default: us-east-1a

  # CIDR of new subnet within this VPC
  SubnetCIDR:
    Description: CIDR of the new subnet within this VPC
    Type: String
    Default: 10.0.1.0/24 

Resources:
  # create VPC
  customVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref NetworkCIDR
      EnableDnsHostnames: 'true'
      EnableDnsSupport: 'true'
      InstanceTenancy: default
      Tags: 
       - Key: Name
         Value: demo-vpc
       - Key: Application
         Value: !Ref 'AWS::StackName'

  # create Internet Gateway
  customIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags: 
       - Key: Name
         Value: demo-igw
       - Key: Application
         Value: !Ref 'AWS::StackName'   

  # attaching the IGW to custom VPC
  vpcToIgw:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref customVPC
      InternetGatewayId: !Ref customIGW

  # create a custom route table for demo vpc
  customRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref customVPC
      Tags: 
       - Key: Name
         Value: demo-public-route-table
       - Key: Application
         Value: !Ref 'AWS::StackName'

  # Add routes entries for public network through igw
  customRoutes:
    Type: AWS::EC2::Route    
    Properties:
      RouteTableId: !Ref customRouteTable
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref customIGW      

  # NACL
  customPublicNACL:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref customVPC
      Tags:
        - Key: Name
          Value: demo-vpc-nacl
        - Key: Application
          Value: !Ref 'AWS::StackName'        

  # Allow all Incoming TCP traffic
  customNaclRulesForInboundTCP:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref customPublicNACL
      RuleNumber: '100'
      Protocol: '6'  # tcp
      RuleAction: allow
      Egress: 'false'  # this rule applies to ingress traffic to the subnet
      CidrBlock: 0.0.0.0/0  # any ip address
      PortRange:
        From: '0'
        To: '65535'

  # Allow all Outgoing TCP traffic
  customNaclRulesForOutboundTCP:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref customPublicNACL
      RuleNumber: '100'
      Protocol: '6'  # tcp
      RuleAction: allow
      Egress: 'true'  # this rule applies to egress traffic from the subnet
      CidrBlock: 0.0.0.0/0
      PortRange:
        From: '0'  # client will be using ephemeral port, using 80 or 22 here will not work
        To: '65535'

  # creating a public subnet
  customPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref customVPC
      AvailabilityZone: !Ref AvailabilityZoneName
      CidrBlock: !Ref SubnetCIDR
      MapPublicIpOnLaunch: true
      Tags: 
      - Key: Name
        Value: 
          !Join 
          - ''
          - - 'public-subnet-'
            - !Ref AvailabilityZoneName
      - Key: Application
        Value: !Ref 'AWS::StackName'

  # asscoiate subnet with our route table else by default it is asscoiated with main route table
  customSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref customPublicSubnet
      RouteTableId: !Ref customRouteTable

  # associate subnet with NACL else by default it is asscoiated with main NACLs
  customSubnetNaclAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      SubnetId: !Ref customPublicSubnet
      NetworkAclId: !Ref customPublicNACL

# output key resources ids and export the values for cross-stack referencing
Outputs:
  VpcID:
      Description: ID of the newly created VPC
      Value: !Ref customVPC
      Export:
        Name: !Sub "${AWS::StackName}-VPCID" # the name for cross referencing

  PublicSubnetID:
      Description: SubnetId of the public subnet
      Value: !Ref customPublicSubnet
      Export:
        Name: !Sub "${AWS::StackName}-SUBNET"